--Database Exploration

--Explore All Objects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES

--Explore All Columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'

--Dimensions Exploration

--Explore All Countries our customer come from
SELECT DISTINCT country FROM gold.dim_customers	

--Explore All Categories "The major Divisions"
SELECT DISTINCT category, subcategory, product_name FROM gold.dim_products
ORDER BY 1, 2, 3

--Date Exploration

--Find the First and Last Order, How many Years of Sales are available
SELECT 
	MIN(order_date) first_order_date,
	MAX(order_date) last_order_date,
	DATEDIFF(year, MIN(order_date), MAX(order_date)) orderdt_ranges_years,
	DATEDIFF(month, MIN(order_date), MAX(order_date)) orderdt_ranges_months
FROM gold.fact_sales

--Find the Youngest and Oldest Customer
SELECT
	MIN(birthdate) youngest_customer,
	MAX(birthdate) oldest_customer,
	DATEDIFF(year, MIN(birthdate), MAX(birthdate)) customers_age_range,
	DATEDIFF(year, MIN(birthdate), GETDATE()) oldest_customer,
	DATEDIFF(year, MAX(birthdate), GETDATE()) youngest_customer
FROM gold.dim_customers

--Measures Exploration

--Find the Total Sales, how many items are sold, Average Selling Price, Total Number of Orders
SELECT
	SUM(sales_amount) total_sales,
	SUM(quantity) total_quantity,
	AVG(price) avg_price,
	COUNT(DISTINCT(order_number)) total_orders
FROM gold.fact_sales

--Find the Total Number of Products
SELECT
	COUNT(product_name) total_products
FROM gold.dim_products

--Find the Total Number of Customers
SELECT 
	COUNT(customer_key) total_customers
FROM gold.dim_customers

--Find the Total Number of Customers that has placed an order
SELECT 
	COUNT(DISTINCT(customer_key)) total_customers
FROM gold.fact_sales
	
--Generate a Report that shows all key metrics of the business	

SELECT 'Total Sales' measure_name, SUM(sales_amount) measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total Orders', COUNT(DISTINCT (order_number)) FROM gold.fact_sales
UNION ALL
SELECT 'Total Products', COUNT(product_name) FROM gold.dim_products
UNION ALL
SELECT 'Total Customers', COUNT(customer_key) FROM gold.dim_customers
UNION ALL
SELECT 'Total Customers that Order', COUNT(DISTINCT (customer_key)) FROM gold.fact_sales

--Magnitude (Compare the Measure Values by Categories)

--Find Total Customers by Countries
SELECT 
	country, 
	COUNT(customer_key) total_customers 
FROM gold.dim_customers 
GROUP BY country 
ORDER BY total_customers DESC

--Find Total Customers by Gender
SELECT 
	gender, 
	COUNT(customer_key) total_customers 
FROM gold.dim_customers 
GROUP BY gender 
ORDER BY total_customers DESC

--Find Total Products by Category
SELECT 
	category, 
	COUNT(product_key) total_products 
FROM gold.dim_products 
GROUP BY category 
ORDER BY total_products DESC

--What is the average costs in each category?
SELECT 
	category, 
	AVG(product_cost) avg_cost 
FROM gold.dim_products 
GROUP BY category
ORDER BY avg_cost DESC

--What is the total revenue generated for each category?
SELECT 
	p.category, 
	SUM(s.sales_amount) total_revenue 
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

--Find total revenue is generated by each_customer
SELECT 
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(s.sales_amount) total_revenue 
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC

--What is the distribution of sold items across countries?
SELECT
	c.country,
	SUM(quantity) item_sold 
FROM gold.fact_sales s 
LEFT JOIN gold.dim_customers c 
ON s.customer_key = c.customer_key 
GROUP BY c.country
ORDER BY item_sold DESC

--Ranking Top N - Bottom N

--Which 5 products generate the highest revenue?
SELECT *
FROM(
SELECT 
	p.product_name,
	SUM(s.sales_amount) total_revenue,
	ROW_NUMBER() OVER(ORDER BY SUM(s.sales_amount) DESC) rev_rank
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.product_name
--ORDER BY total_revenue DESC
)t
WHERE rev_rank <= 5


--What are the 5 worst-performing products in terms of sales?
SELECT *
FROM(
SELECT TOP 5
	p.product_name,
	SUM(s.sales_amount) total_revenue,
	ROW_NUMBER() OVER(ORDER BY SUM(s.sales_amount)) rev_rank
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.product_name
--ORDER BY total_revenue 
)t
WHERE rev_rank <= 5

--Find the Top 10 Customers who have generated the Highest Revenue
SELECT TOP 10
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(s.sales_amount) total_revenue 
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC

SELECT TOP 10 
	sales_amount
FROM gold.fact_sales

--Find the 3 Customers with the Fewer Orders Placed
SELECT TOP 3
	c.customer_key,
	c.first_name,
	c.last_name,
	COUNT(DISTINCT(order_number)) total_orders
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_orders
